views.sort.views_random_seed_random:
  type: views_sort
  label: 'Standard'
  mapping:
    user_seed_type:
      type: string
      label: 'User seed type'
    reset_seed_int:
      type: integer
      label: 'Reset seed'
    reset_seed_custom:
      type: string
      label: 'Custom reset seed'
